
code['a'] = new QList<ditdah>();
*(code['a']) << DIT << DAH;
code['b'] = new QList<ditdah>();
*(code['b']) << DAH << DIT << DIT << DIT;
code['c'] = new QList<ditdah>();
*(code['c']) << DAH << DIT << DAH << DIT;
code['d'] = new QList<ditdah>();
*(code['d']) << DAH << DIT << DIT;
code['e'] = new QList<ditdah>();
*(code['e']) << DIT;
code['f'] = new QList<ditdah>();
*(code['f']) << DIT << DIT << DAH << DIT;
code['g'] = new QList<ditdah>();
*(code['g']) << DAH << DAH << DIT;
code['h'] = new QList<ditdah>();
*(code['h']) << DIT << DIT << DIT << DIT;
code['i'] = new QList<ditdah>();
*(code['i']) << DIT << DIT;
code['j'] = new QList<ditdah>();
*(code['j']) << DIT << DAH << DAH << DAH;
code['k'] = new QList<ditdah>();
*(code['k']) << DAH << DIT << DAH;
code['l'] = new QList<ditdah>();
*(code['l']) << DIT << DAH << DIT << DIT;
code['m'] = new QList<ditdah>();
*(code['m']) << DAH << DAH;
code['n'] = new QList<ditdah>();
*(code['n']) << DAH << DIT;
code['o'] = new QList<ditdah>();
*(code['o']) << DAH << DAH << DAH;
code['p'] = new QList<ditdah>();
*(code['p']) << DIT << DAH << DAH << DIT;
code['q'] = new QList<ditdah>();
*(code['q']) << DAH << DAH << DIT << DAH;
code['r'] = new QList<ditdah>();
*(code['r']) << DIT << DAH << DIT;
code['s'] = new QList<ditdah>();
*(code['s']) << DIT << DIT << DIT;
code['t'] = new QList<ditdah>();
*(code['t']) << DAH;
code['u'] = new QList<ditdah>();
*(code['u']) << DIT << DIT << DAH;
code['v'] = new QList<ditdah>();
*(code['v']) << DIT << DIT << DIT << DAH;
code['w'] = new QList<ditdah>();
*(code['w']) << DIT << DAH << DAH;
code['x'] = new QList<ditdah>();
*(code['x']) << DAH << DIT << DIT << DAH;
code['y'] = new QList<ditdah>();
*(code['y']) << DAH << DIT << DAH << DAH;
code['z'] = new QList<ditdah>();
*(code['z']) << DAH << DAH << DIT << DIT;
code['0'] = new QList<ditdah>();
*(code['0']) << DAH << DAH << DAH << DAH << DAH;
code['1'] = new QList<ditdah>();
*(code['1']) << DIT << DAH << DAH << DAH << DAH;
code['2'] = new QList<ditdah>();
*(code['2']) << DIT << DIT << DAH << DAH << DAH;
code['3'] = new QList<ditdah>();
*(code['3']) << DIT << DIT << DIT << DAH << DAH;
code['4'] = new QList<ditdah>();
*(code['4']) << DIT << DIT << DIT << DIT << DAH;
code['5'] = new QList<ditdah>();
*(code['5']) << DIT << DIT << DIT << DIT << DIT;
code['6'] = new QList<ditdah>();
*(code['6']) << DAH << DIT << DIT << DIT << DIT;
code['7'] = new QList<ditdah>();
*(code['7']) << DAH << DAH << DIT << DIT << DIT;
code['8'] = new QList<ditdah>();
*(code['8']) << DAH << DAH << DAH << DIT << DIT;
code['9'] = new QList<ditdah>();
*(code['9']) << DAH << DAH << DAH << DAH << DIT;
