Cute CW: train yourself

* Introduction

  I've had thoughts for a long time about how we train ourselves in CW
  ("Carrier Wave" otherwise known as Morse Code).  After preparing for a
  presentation about learning CW I realized software could really help
  us out in ways not yet seen.  This is my effort to help decrease the
  pain in training your brain to understand Morse Code.

* Get it!

  You can download the source code or pre-built binaries from:

    http://www.hamtools.org/qtcw/

  You can also access the git repository, provided by githib, from:

    http://www.github.com/hardaker/CuteCW/

* The TODO list
*** TODO More Fun Games!
*** TODO Add a "test" button next to the frequency set spinbox
*** TODO fix the probability for bad letters
***** Example case with L good letters and 1 bad one:
      + P = percent correct of the "bad" letter (eg, 50)
      + L = # of letters at O%
      + O = percent correct of the good letter (eg, 100)
      + T = target probability (eg, .5)
      + N = magic constant

***** probability calculation:
      t=(n-p)/(l*n-lo+n-p)

***** solved for N
      n = ((p+lo)*t-p)/((l+1)*t-1) 

      Note: fails at l = 1 with inf/inf

***** Values for N given L
      |----+------------------|
      |  L |                N |
      |----+------------------|
      |  2 |              150 |
      |  3 |              125 |
      |  4 | 116.666666666667 |
      |  5 |            112.5 |
      |  6 |              110 |
      |  7 | 108.333333333333 |
      |  8 | 107.142857142857 |
      |  9 |           106.25 |
      | 10 | 105.555555555556 |
      | 26 |              102 |
      |----+------------------|

***** Plotting the probability graph with gnuplot

      plot [0:100] f(p)=(n-p)/((l*n-l*o) + n - p), n=102, l=26, o=100, f(x)
